chat/chat/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('', include('chatapp.urls'))
]

urlpatterns+= static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

chat/chatapp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('groupchat/', views.chat, name='chat'),
    path('contact/',views.contact, name='contact')
]

chat/users/urls.py
from django.urls import path
from . import views
from .views import UserCreationView,ProfileEdit
urlpatterns = [
    path('signup/' , UserCreationView.as_view(), name='signup'),
    path('logoutpage/', views.logoutView, name='logoutpage'),
    path('profile/', views.profileView, name='profile'),
    path('editprofile/', ProfileEdit.as_view(), name='editprofile')
]

chat/chatapp/models.py
from django.db import models
from django.conf import settings

class Messages(models.Model):
    text = models.TextField()
    message_author = models.CharField(max_length=100,null=True)
    date = models.DateTimeField(auto_now_add=True)

class MessagesToAdmin(models.Model):
    full_name = models.CharField(max_length=50)
    email = models.EmailField()
    text = models.TextField()

chat/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    username = models.CharField(max_length=20, unique=True, null=True)

chat/chatapp/forms.py
from .models import Messages,MessagesToAdmin
from django import forms
from django.forms import ModelForm


class MessageForm(forms.ModelForm):
    class Meta:
        model = Messages
        fields = ('text','message_author')

class MessageToAdminForm(forms.ModelForm):
    class Meta:
        model = MessagesToAdmin
        fields = '__all__'

chat/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import CustomUser

class UserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields+('first_name', 'last_name', 'email','username')
class UserChangeForm(UserChangeForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField()
    username = forms.CharField(max_length=20)
    class Meta(UserChangeForm):
        model = CustomUser
        fields = ('first_name', 'last_name', 'email','username')

chat/chatapp/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from .models import Messages
from .forms import MessageForm,MessageToAdminForm
from django.shortcuts import redirect

def login_required_view(function):
    def wrapper(request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        return function(request, *args, **kwargs)
    return wrapper

@login_required_view
def chat(request):
    messages = Messages.objects.all()
    form = MessageForm()
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
            instance = form.save(commit=False) 
            instance.save()
    context = {'messages': messages , 'form': form}
    return render(request, 'chat.html', context)
def home(request):
    return render(request, 'home.html')
def contact(request):
    form = MessageToAdminForm()
    if request.method == "POST":
        form = MessageToAdminForm(request.POST)
        if form.is_valid():
            form.save()
    context = {'form':form}
    return render(request, 'contact.html', context)

chat/users/views.py
from django.shortcuts import render
from .forms import UserCreationForm,UserChangeForm
from django.urls import reverse_lazy
from django.views.generic import CreateView,UpdateView
from .models import CustomUser
from django.shortcuts import redirect

def login_required_view(function):
    def wrapper(request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        return function(request, *args, **kwargs)
    return wrapper

class UserCreationView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'
def logoutView(request):
    return render(request, 'logoutpage.html')
@login_required_view
def profileView(request):
    return render(request, 'profile.html')
class ProfileEdit(UpdateView):
    form_class = UserChangeForm
    model = CustomUser
    template_name = 'profileedit.html'
    success_url = reverse_lazy('profile')
    
    def get_object(self):
        return self.request.user

chat/templates/chat.html
{% extends 'home.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}



    <style>
        #id_message_author{
            display: none;
        }
        #fixed-input {
          position: fixed;
          top: 93%;
          width: 80%;
          height: 7%;
          transform: translate(12.5%);
        }
        #fixed-input input{
            height: 100%;
        }
        #fixed-input button{
            height: 100%;
            
        }
      </style> 


    <center>
        <div class="card" style="width: 80%; ">
            <div class="card-header"><h2>Anonym Chat</h2></div>
                <div class="card-body"><ul class="list-group">
                    {% for message in messages %}
                    
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                        {{message.text}}
                        <span class="badge badge-primary badge-pill">{{message.date}} | {{message.message_author}}</span>
                        </li>
                    
                    {% endfor %}</ul>
                </div>
                </div>
            <footer class="blockquote-footer">
                <form method="post">
                    {% csrf_token %}
                    <input type="text" class="form-control" name="message_author" id="id_message_author" value="{{user.username}}" aria-label="Recipient's username" aria-describedby="basic-addon2" >
                    <div class="input-group mb-3" id="fixed-input">
                        <input type="text" class="form-control" name="text" id="id_text" placeholder="Write your message" aria-label="Recipient's username" aria-describedby="basic-addon2" >
                        <div class="input-group-append">
                          <button class="btn btn-secondary" type="submit">Send</button>
                        </div>
                      </div>
                </form>
            </footer>
        </div>
    </center>



    <script>
        document.addEventListener("DOMContentLoaded", function() {
          var ul = document.querySelector(".list-group");
          var liList = Array.from(ul.getElementsByTagName("li"));
          liList.reverse();
    
          while (ul.firstChild) {
            ul.removeChild(ul.firstChild);
          }
    
          for (var i = 0; i < liList.length; i++) {
            ul.appendChild(liList[i]);
          }
        });
      </script>
    {% endblock content %}
</body>
</html>

chat/templates/contact.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/contact.css' %}">
<div class="background">
    <div class="container">
      <div class="screen">
        <div class="screen-header">
          <div class="screen-header-left">
            <div class="screen-header-button close"></div>
            <div class="screen-header-button maximize"></div>
            <div class="screen-header-button minimize"></div>
          </div>
          <div class="screen-header-right">
            
            <div class="screen-header-ellipsis"></div>
            <div class="screen-header-ellipsis"></div>
            <div class="screen-header-ellipsis"></div>
          </div>
        </div>
        <div class="screen-body">
          <div class="screen-body-item left">
            <div class="app-title">
              <span>CONTACT</span>
              <span>US</span>
            </div>
            <div class="app-contact">CONTACT INFO : +998 (91) 316-67-36</div>
            <div class="app-contact">EMAIL : <a href=mailto:ravshanovdaler06@gmail.com>ravshanovdaler06@gmail.com</a></div>
          </div>
          <div class="screen-body-item">
            <div class="app-form">
                <form method="post">
                    {% csrf_token %}
              <div class="app-form-group">
                <input class="app-form-control" placeholder="NAME" name="full_name" id="id_full_name">
              </div>
              <div class="app-form-group" >
                <input class="app-form-control" placeholder="EMAIL" name="email" id="id_email">
              </div>
              <div class="app-form-group message" >
                <input class="app-form-control" placeholder="MESSAGE" name="text" id="id_text">
              </div>
              <div class="app-form-group buttons">
               <a href="{% url 'home' %}"><button class="app-form-button">CANCEL</button></a>
                <button class="app-form-button" type="submit">SEND</button>
              </div>
            </div>
        </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

chat/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown" style="margin-right: 4%;">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'chat' %}">Group Chat</a>
              </li>
                {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Contact us</a>
              </li>
            </ul>
            {% if user.is_authenticated %}
            <ul class="navbar-nav"> <!-- Added a new unordered list for dropdown menu -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{user.username}}
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'editprofile' %}">Edit Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'profile' %}">View Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'logoutpage' %}">LogOut</a></li>
                {% else %}
                    <a href="{% url 'signup' %}"><button class="btn btn-primary" >SignUp</button></a>
                    <a href="{% url 'login' %}"><button class="btn btn-secondary" >LogIn</button></a>
                </ul>
              </li>
            </ul>
            {% endif %}
          </div>
        </div>
      </nav>

      {% block content %}
      <link rel="stylesheet" href="{% static 'css/home.css' %}">
      <center>
      <div class="card text-center" id="main">
        <div class="card-header">
          Featured
        </div>
        <div class="card-body">
          <h5 class="card-title">Anonymous Chatting Website</h5>
          <p class="card-text">In this Website you can chat with people anonymously and can make friends</p>
          <img src="{% static 'images/chatting.jfif' %}" alt="it's your problem">
          <br>
          <a href="{% url 'chat' %}" class="btn btn-primary">Start Messaging</a>
        </div>
        <div class="card-footer text-muted">
          2 days ago
        </div>
      </div>
      </center>
      {% endblock content %}


</body>
</html>

chat/templates/logoutpage.html
{% extends 'home.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <style>
        a:link {
            text-decoration: none;
        }
        button{
            width: 10%;
            margin: 3%;
        }
    </style>
        <center>
            <h1>Do you really want to logout?</h1>
            <a href="{% url 'home' %}">
            <button type="button" class="btn btn-primary">
                    <i style="color: white;">Cancel</i>
            </button></a>
            <a href="{% url 'logout' %}">
            <button type="button" class="btn btn-danger"><a href="{% url 'logout' %}" style="color: white;">
                <i style="color: white;">Logout</i>
           </button> </a>
        </center>
    {% endblock content %}
</body>
</html>

chat/templates/profile.html
{% extends 'home.html' %}


{% block content %}

<section class="vh-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-12 col-xl-4">
  
          <div class="card" style="border-radius: 15px;">
            <div class="card-body text-center">
              <div class="mt-3 mb-4">
                <svg  xmlns="http://www.w3.org/2000/svg" width="70%" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                  </svg>
              </div>
              <h4 class="mb-2">{{user.first_name}} {{user.last_name}} </h4>
              <p class="text-muted mb-4">@{{user.username}} <span class="mx-2">|</span> <a
                  href="#!">{{ user.email }}</a></p>
                  <a href="{% url 'editprofile' %}">
              <button type="button" class="btn btn-primary btn-rounded btn-lg">
                Edit Profile  
              </button>
            </a>
                <a href="{% url 'password_change' %}">
              <button type="button" class="btn btn-primary btn-rounded btn-lg" style="font-size: 18px;">
                Change Password
              </button>
                <a href="{% url 'password_reset' %}">
              <button type="button" class="btn btn-primary btn-rounded btn-lg" style="margin-top: 1%;">
                Reset Password 
              </button></a>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

chat/templates/profileedit.html
{% extends 'home.html' %}


{% block content %}

    <style>
        .bodydiv{margin-top:20px;}
            .avatar{
                width:200px;
                height:200px;
        }
        button{
            float: right;
            height: 10%;
            width: 20%;
        }		
    </style>


    <form method="post">{% csrf_token %}
    <div class="bodydiv">
        <div class="container bootstrap snippets bootdey">
            <h1 class="text-primary">Edit Profile</h1>
              <hr>
            <div class="row">
              <!-- left column -->
              <div class="col-md-3">
                <div class="text-center">
                    <svg  xmlns="http://www.w3.org/2000/svg" width="70%" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                      </svg>
                  
                </div>
              </div>
              
              <!-- edit form column -->
              <div class="col-md-9 personal-info">
                <h3>Personal info</h3>
                
                <form class="form-horizontal" role="form">
                  <div class="form-group">
                    <label class="col-lg-3 control-label">First name:</label>
                    <div class="col-lg-8">
                        <input type="text" name="first_name" value="{{user.first_name}}" maxlength="100" required id="id_first_name" class="form-control">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-lg-3 control-label">Last name:</label>
                    <div class="col-lg-8">
                        <input type="text" name="last_name" value="{{user.last_name}}" maxlength="100" required id="id_last_name" class="form-control">
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-lg-3 control-label">Username:</label>
                    <div class="col-lg-8">
                        <input type="text" name="username" value="{{user.username}}" maxlength="20" required id="id_username" class="form-control">
                        <ul>
                            {% for error in form.username.errors %}
                                <li class="text-danger">{{error}}</li>
                            {% endfor %}
                            </ul>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-lg-3 control-label">Email:</label>
                    <div class="col-lg-8">
                        <input type="email" name="email" value="{{user.email}}" required id="id_email" class="form-control">
                    </div>
                  </div>
                  <button class="btn btn-primary" type="submit">Save</button>
                        </select>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
          </div>
        </div>
        <hr>
    </form>
</div>
{% endblock content %}

chat/templates/signup.html
{% extends 'home.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <link rel="stylesheet" href="{% static 'css/registration.css' %}">
    <div class="container">
        <h2 style="text-align: center;">Sign Up</h2>
        <i style="font-size: 15px;"><a href="{% url 'home' %}" style="color: black;"><img src="https://www.svgrepo.com/show/326885/arrow-back-circle-sharp.svg" style="height: 30px; width: 30px;">back</a></i>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" name="username" maxlength="20" autofocus required id="id_username">
                <ul>
                {% for error in form.username.errors %}
                    <li class="text-danger">{{error}}</li>
                {% endfor %}
                </ul>
            </div>

            <div class="form-group">
                <label for="firstName">First Name:</label>
                <input type="text" name="first_name"  maxlength="100" required id="id_first_name">
                <ul>
                {% for error in form.first_name.errors %}
                    <li class="text-danger">{{error}}</li>
                {% endfor %}</ul>
            </div>

            <div class="form-group">
                <label for="lastName">Last Name:</label>
                <input type="text" name="last_name"  maxlength="100" required id="id_last_name">
                <ul>
                {% for error in form.last_name.errors %}
                    <li class="text-danger">{{error}}</li>
                {% endfor %}</ul>
            </div>

            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" name="email"  maxlength="254" required id="id_email">
              </div>

            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" name="password1" autocomplete="new-password" required id="id_password1">
                <ul>
                {% for error in form.password1.errors %}
                    <li class="text-danger">{{error}}</li>
                {% endfor %}</ul>
            </div>

            <div class="form-group">
                <label for="confirmPassword">Confirm Password:</label>
                <input type="password" name="password2" autocomplete="new-password" required id="id_password2">
                <ul>
                {% for error in form.password2.errors %}
                    <li class="text-danger">{{error}}</li>
                {% endfor %}</ul>
            </div>
            
            <button type="submit" class="btn btn-primary" style="border-radius: 20px;">Sign Up</button>
        </form>
    </div>
    {% endblock content %}
</body>
</html>